name: Auto Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create ZIP Archive
        run: |
          zip -r GutsyDawn.zip . -x ".git/*" -x ".github/*"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: GutsyDawn.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
